import Head from 'next/head'
import Image from 'next/image'
import requests from '../data/requests'
import Header from '../presentation/components/Header'
import NavBar from '../presentation/components/NavBar'
import Results from '../presentation/components/Results'

export default function Home(props) {
  console.log(props)
  const results = props.results;
  return (
    <div >
      <Head>
        <title>Hulu Don</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     

      {/* Header  */}
      <Header/>

      {/* Nav  */}
      <NavBar/>

      {/* Results  */}
      <Results results={results}/>
    </div>
  )
}
 
export async function getServerSideProps(context){
  const genre = context.query.genre;
  
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`
  ).then(res => res.json());

  return {
    props: {
      results: request.results,
    }
  }
}